# Generated by Django 5.2.11 on 2026-04-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_notificaciones_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="procedimientoautoevaluacion",
            old_name="procedimiento",
            new_name="sop_op_procedimiento",
        ),
    ]
