# Generated by Django 5.2.11 on 2026-04-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0008_rename_procedimiento_procedimientoautoevaluacion_sop_op_procedimiento",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="borradorautoevaluacion",
            old_name="procedimiento",
            new_name="sop_op_procedimiento",
        ),
    ]
