# Generated by Django 5.2.11 on 2026-04-28 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_estudiante_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinadorCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cedula_coord_curso", models.IntegerField(unique=True)),
                ("nombre_1", models.CharField(max_length=100)),
                ("nombre_2", models.CharField(blank=True, max_length=100, null=True)),
                ("apellido_1", models.CharField(max_length=100)),
                ("apellido_2", models.CharField(blank=True, max_length=100, null=True)),
                ("curso", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
