# Generated by Django 5.2.11 on 2026-04-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_coordinadorcurso"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="coordinadorcurso",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.coordinadorcurso",
            ),
            preserve_default=False,
        ),
    ]
