# Generated by Django 5.2.11 on 2026-05-04 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_profesor_coordinadorcurso"),
    ]

    operations = [
        migrations.CreateModel(
            name="CohorteIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.IntegerField()),
                ("periodo", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="estudiante",
            name="cohorte",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.cohorteingreso",
            ),
        ),
    ]
