# Generated by Django 5.2.11 on 2026-05-04 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_cohorteingreso_estudiante_cohorte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="cohorte",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="app.cohorteingreso",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="cohorteingreso",
            unique_together={("anio", "periodo")},
        ),
    ]
