# Generated by Django 5.2.11 on 2026-05-04 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_estudiante_cargado_por_alter_estudiante_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estudiante",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
